[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --no-location --chip RP2040"
#runner = "probe-rs run --no-location --chip RP2350"
#runner = "elf2uf2-rs -d"
#runner = "picotool load -u -v -x -t elf"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "warn,pico1541_rs=debug"
